quarkus.container-image.name=service-analytics
quarkus.container-image.tag=1.0.0-SNAPSHOT
quarkus.index-dependency.common-modules.group-id=com.sodep
quarkus.index-dependency.common-modules.artifact-id=common-modules
quarkus.hibernate-orm.database.generation=none
