quarkus.container-image.name=service-transactions
quarkus.container-image.tag=1.0.0-SNAPSHOT
quarkus.arc.scan-dependency.common-modules.group-id=com.sodep
quarkus.arc.scan-dependency.common-modules.artifact-id=common-modules
quarkus.index-dependency.common-modules.group-id=com.sodep
quarkus.index-dependency.common-modules.artifact-id=common-modules
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
quarkus.datasource.username=${POSTGRES_USER}
quarkus.datasource.password=${POSTGRES_PASSWORD}
quarkus.hibernate-orm.database.generation=none
quarkus.flyway.migrate-at-start=true
quarkus.flyway.locations=db/migration
quarkus.log.level=DEBUG
