apiVersion: v1
kind: Service
metadata:
  name: service-bank
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: bank
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bank
  template:
    metadata:
      labels:
        app: bank
    spec:
      containers:
        - name: bank
          image: service-bank:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          envFrom:
            - configMapRef:
                name: service-bank-config
            - secretRef:
                name: bank-secret
          env:
            - name: JWT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: bank-secret
                  key: JWT_TOKEN
            - name: MIDDLEWARE_URL
              valueFrom:
                configMapKeyRef:
                  name: service-bank-config
                  key: MIDDLEWARE_URL
