# Archivo: k8s/overlays/dev/postgres-db.yaml
apiVersion: v1
kind: Service
metadata:
  name: postgres-shared-db
spec:
  ports:
    - port: 5432
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: quay.io/sclorg/postgresql-15-c9s
          envFrom:
            - secretRef:
                name: postgres-secret
          ports:
            - containerPort: 5432
