apiVersion: v1
kind: Service
metadata:
  name: service-transactions
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30001
---
apiVersion: v1
kind: Service
metadata:
  name: service-analytics
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30002
